#!/bin/bash

set -e

# Install OptiMathSat
wget http://optimathsat.disi.unitn.it/releases/optimathsat-1.6.4/optimathsat-1.6.4-linux-64-bit.tar.gz
tar xzf optimathsat-1.6.4-linux-64-bit.tar.gz
mv optimathsat-1.6.4-linux-64-bit /home/${NB_USER}/optimathsat

# Install MiniZinc
wget https://github.com/MiniZinc/libminizinc/archive/2.3.2.tar.gz
tar xf 2.3.2.tar.gz
mv libminizinc-2.3.2 minizinc
cd minizinc && mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
cd ../share/minizinc/
wget http://optimathsat.disi.unitn.it/data/smt2.tar.gz
tar xf smt2.tar.gz
rm smt2.tar.gz
cd /home/${NB_USER}

# Install Z3
git clone https://github.com/Z3Prover/z3
# cd z3
# python scripts/mk_make.py
# cd build
# make

# Clone fzn2omt
git clone https://github.com/PatrickTrentin88/fzn2omt.git
